add_newline = false

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"

[directory]
truncation_length = 8
style = "bold magenta"

[character]
symbol = "λ"
vicmd_symbol = ""
style_success = "bold purple"
style_failure = "bold purple"
use_symbol_for_status = false

[memory_usage]
disabled = false
show_percentage = true
show_swap = false
threshold = -1
symbol = " "
separator = ", "
style = "bold green"

[git_branch]
style = "bold red"

[git_commit]
disabled = false
commit_hash_length = 4

[git_state]
cherry_pick = "🍒"
rebase = "⏚ "
merge = " "

[git_status]
prefix = ""
suffix = ""
