add_newline = false

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"

[directory]
truncation_length = 8
style = "purple"

[character]
symbol = "λ"
vicmd_symbol = ""
style_success = "blue"
style_failure = "magenta"
use_symbol_for_status = false

[memory_usage]
disabled = false
show_percentage = true
show_swap = false
threshold = -1
symbol = " "
separator = ", "
style = "bold green"

[git_commit]
disabled = false
commit_hash_length = 4

[git_state]
cherry_pick = "🍒"
rebase = "⏚"
merge = ""

[git_status]
deleted = " "
untracked = " "
stashed = " "
modified = " "
prefix = ""
suffix = ""
